
mazecon_topic:
    resource: "@MazeconTopicBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


mazecon_topic_api_rest:
    resource: "@MazeconTopicBundle/Resources/config/routing_rest_api.yml"
    type: rest
    prefix: /api
