# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN:  ROLE_ADMIN


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /topic
                csrf_token_generator: security.csrf.token_manager
                # csrf_provider: form.csrf_provider
                # if you are using Symfony < 2.8, use the following config instead

            logout:
                path:     /logout
                target:   /topic
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/topicuserview,    role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/topic,     role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/home,      role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/*,         role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/profile,   role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/profile/,  role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/admin/,    role: ROLE_ADMIN}
        - { path: ^/admin,     role: ROLE_ADMIN}
        - { path: ^/add,       role: ROLE_ADMIN}
        - { path: ^/remove,    role: ROLE_ADMIN}
        - { path: ^/edit,      role: ROLE_ADMIN}