<?php

namespace Mazecon\TopicBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedASC(){
        $queryBuilder = $this->createQueryBuilder('t')
            ->join('t.user', 'u');
        return $queryBuilder->getQuery();
    }
}
