<?php

namespace Mazecon\TopicBundle\Repository;

/**
 * TopicUserViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicUserViewRepository extends \Doctrine\ORM\EntityRepository
{
}
