<?php

namespace Mazecon\TopicBundle\Repository;

/**
 * UserFOSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFOSRepository extends \Doctrine\ORM\EntityRepository
{
}
